version: '3.6'

services:
  nginx:
    container_name: bayer-nginx
    image: nginx
    networks:
      nginx:
        aliases:
          - php.bayer.sutunam
    ports:
      - '${HOST_IP:-0.0.0.0}:80:80'
      - '${HOST_IP:-0.0.0.0}:443:443'
    volumes:
      - './:/php'
      - './docker/nginx/php.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php

  php:
    container_name: bayer-php
    image: bayer-php
    build:
      context: './docker/php'
      args:
        UID: "${UID}"
        GID: "${GID}"
    volumes:
      - './:/php'
    networks:
      - nginx
      - php
    depends_on:
      - mysql

  node:
    container_name: bayer-node
    image: bayer-node
    build:
      context: './docker/node'
      args:
        UID: "${UID}"
        GID: "${GID}"
    volumes:
      - './:/app'

  mysql:
    container_name: bayer-mysql
    image: mysql:5.7
    env_file:
      - './docker/mysql/.env'
    volumes:
      - './docker/mysql/data:/var/lib/mysql'
    networks:
      - php

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: bayer-phpmyadmin
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql
    networks:
      - php
    ports:
      - '${PMA_PORT:-8080}:80'

networks:
  nginx:
  php:

volumes:
  esdata:
